### ISSUE TITLE
docs for noobs

### ISSUE THREAD

**Issue by crybo** [morvaridio/hdtools#2]
Hi,
for newb like me, it will be great if there's more document on how to use your lib. for example, how to use it on testnet?

**Comment by professormahi** [comment]
We use BIP44 which is based on BIP32. It dedicates following derivation path:
> m / purpose' / coin_type' / account' / change / address_index

- purpose: `44.`, `49.`, or `84.` for BIP44, BIP49, and BIP84.
- coin_type: `0.` for Bitcoin, and `1.` for Bitcoin Testnet

You can compare the derived addresses and keys with https://iancoleman.io/bip39/.
